In [2]:

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 定義一個隨機數（標量）
random_float = tf.random.uniform(shape=())

# 定義一個有2個元素的零向量
zero_vector = tf.zeros(shape=(2))

# 定義兩個2×2的常量矩陣
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])


In [3]:
# 查看矩陣A的形狀、類型和值
print(A.shape)      # 輸出(2, 2)，即矩陣的長和寬均為2
print(A.dtype)      # 輸出<dtype: 'float32'>
print(A.numpy())    # 輸出[[1. 2.]
                    #      [3. 4.]]

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [4]:
C = tf.add(A, B)    # 計算矩陣A和B的和
D = tf.matmul(A, B) # 計算矩陣A和B的乘積
C

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [5]:
D

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [6]:
x = tf.Variable(initial_value=5.)

# 在 tf.GradientTape() 的上下文內，所有計算步驟都會被記錄以用於求導
with tf.GradientTape() as tape:
    y = tf.square(x)
y_grad = tape.gradient(y, x)        # 計算y關於x的導數
print(y,'\n',y_grad)

tf.Tensor(25.0, shape=(), dtype=float32) 
 tf.Tensor(10.0, shape=(), dtype=float32)


In [7]:
X = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[1.], [2.]])
w = tf.Variable(initial_value=[[1.], [2.]])
b = tf.Variable(initial_value=1.)
with tf.GradientTape() as tape:
    L = tf.reduce_sum(tf.square(tf.matmul(X, w) + b - y))
w_grad, b_grad = tape.gradient(L, [w, b])        # 計算L(w, b)關於w, b的偏導數
print(L, w_grad, b_grad,sep='\n')

tf.Tensor(125.0, shape=(), dtype=float32)
tf.Tensor(
[[ 70.]
 [100.]], shape=(2, 1), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [8]:
X_raw = np.array([2013, 2014, 2015, 2016, 2017], dtype=np.float32)
y_raw = np.array([12000, 14000, 15000, 16500, 17500], dtype=np.float32)

X = (X_raw - X_raw.min()) / (X_raw.max() - X_raw.min())
y = (y_raw - y_raw.min()) / (y_raw.max() - y_raw.min())


In [9]:
#NumPy 下的線性回歸
a, b = 0, 0

num_epoch = 10000
learning_rate = 5e-4
for e in range(num_epoch):
    # 手動計算損失函數關於自變數（模型參數）的梯度
    y_pred = a * X + b
    grad_a, grad_b = 2 * (y_pred - y).dot(X), 2 * (y_pred - y).sum()

    # 更新參數
    a, b = a - learning_rate * grad_a, b - learning_rate * grad_b

print(a, b)


0.9763702027872223 0.057564988337455304


In [3]:
a = tf.constant(3)

In [5]:
print(a)
tf.print(a)

tf.Tensor(3, shape=(), dtype=int32)
3
